# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protocol/v1/common.proto\x12\x0bprotocol.v1\"\xe1\x01\n\rMessageHeader\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t\x12\x11\n\tanchor_id\x18\x05 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x06 \x01(\x03\x12\x13\n\x0bunity_frame\x18\x07 \x01(\x03\x12\x16\n\x0esender_mono_ms\x18\x08 \x01(\x01\x12\x17\n\x0f\x63reated_unix_ms\x18\t \x01(\x01\x12\x16\n\x0eschema_version\x18\n \x01(\t\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"2\n\x04Quat\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"R\n\x06Pose3D\x12#\n\x08position\x18\x01 \x01(\x0b\x32\x11.protocol.v1.Vec3\x12#\n\x08rotation\x18\x02 \x01(\x0b\x32\x11.protocol.v1.Quat\"\x1b\n\tMatrix4x4\x12\x0e\n\x06values\x18\x01 \x03(\x01\";\n\tErrorInfo\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t\"e\n\x0bTimingStats\x12\x0f\n\x07yolo_ms\x18\x01 \x01(\x01\x12\x10\n\x08\x64\x65pth_ms\x18\x02 \x01(\x01\x12\x10\n\x08\x63utie_ms\x18\x03 \x01(\x01\x12\x0f\n\x07pose_ms\x18\x04 \x01(\x01\x12\x10\n\x08total_ms\x18\x05 \x01(\x01\"\xbf\x01\n\nCommandAck\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.protocol.v1.MessageHeader\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x11\n\tduplicate\x18\x03 \x01(\x08\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12%\n\x05\x65rror\x18\x06 \x01(\x0b\x32\x16.protocol.v1.ErrorInfo\x12\x18\n\x10\x61\x63\x63\x65pted_mono_ms\x18\x07 \x01(\x01\x42\x18\xaa\x02\x15\x45goAnchor.Protocol.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'egoanchor.protocol.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\025EgoAnchor.Protocol.V1'
  _globals['_MESSAGEHEADER']._serialized_start=42
  _globals['_MESSAGEHEADER']._serialized_end=267
  _globals['_VEC3']._serialized_start=269
  _globals['_VEC3']._serialized_end=308
  _globals['_QUAT']._serialized_start=310
  _globals['_QUAT']._serialized_end=360
  _globals['_POSE3D']._serialized_start=362
  _globals['_POSE3D']._serialized_end=444
  _globals['_MATRIX4X4']._serialized_start=446
  _globals['_MATRIX4X4']._serialized_end=473
  _globals['_ERRORINFO']._serialized_start=475
  _globals['_ERRORINFO']._serialized_end=534
  _globals['_TIMINGSTATS']._serialized_start=536
  _globals['_TIMINGSTATS']._serialized_end=637
  _globals['_COMMANDACK']._serialized_start=640
  _globals['_COMMANDACK']._serialized_end=831
# @@protoc_insertion_point(module_scope)

