"""定性 replay 采集校验、模型重投影和六行连续轨迹图的包级入口。"""

from __future__ import annotations

from .contracts import (
    FORMAT_NAME,
    FORMAT_VERSION,
    VARIANT_COLORS_HEX,
    VARIANT_IDS,
    ReplayCapture,
    ReplayManifest,
    ReplaySample,
    load_capture,
)
from .geometry import (
    UNITY_TO_CV_BASIS,
    display_world_to_cv_camera,
    pose_to_matrix,
    projection_mesh_local_matrix,
    recorded_projection_matrix,
    verify_projection_matrix,
)
from .render import (
    ROW_IDS,
    ROW_KEYS,
    ROW_TITLES,
    GridColumn,
    MeshProjector,
    describe_samples,
    render_comparison_grid,
    render_frame_overlays,
    select_samples_by_ids,
    select_stride_samples,
)
from .settings import (
    COLUMN_LABEL_MODES,
    DEFAULT_REPLAY_CONFIG_PATH,
    TIMELINE_MODES,
    TIMELINE_PLACEMENTS,
    AxesSettings,
    CropSettings,
    LayoutSettings,
    OverlaySettings,
    ReplayConfigProvenance,
    ReplaySettings,
    SelectionSettings,
    TimelineSettings,
    load_replay_settings,
)
from .texture_renderer import TEXTURE_RENDER_BACKENDS

__all__ = [
    "FORMAT_NAME",
    "FORMAT_VERSION",
    "COLUMN_LABEL_MODES",
    "VARIANT_COLORS_HEX",
    "VARIANT_IDS",
    "UNITY_TO_CV_BASIS",
    "ROW_IDS",
    "ROW_KEYS",
    "ROW_TITLES",
    "DEFAULT_REPLAY_CONFIG_PATH",
    "AxesSettings",
    "CropSettings",
    "GridColumn",
    "LayoutSettings",
    "MeshProjector",
    "OverlaySettings",
    "ReplayCapture",
    "ReplayConfigProvenance",
    "ReplayManifest",
    "ReplaySample",
    "ReplaySettings",
    "SelectionSettings",
    "TEXTURE_RENDER_BACKENDS",
    "TIMELINE_MODES",
    "TIMELINE_PLACEMENTS",
    "TimelineSettings",
    "display_world_to_cv_camera",
    "describe_samples",
    "load_capture",
    "load_replay_settings",
    "pose_to_matrix",
    "projection_mesh_local_matrix",
    "recorded_projection_matrix",
    "render_comparison_grid",
    "render_frame_overlays",
    "select_samples_by_ids",
    "select_stride_samples",
    "verify_projection_matrix",
]
